// lib/models/habit.dart

import 'package:hive/hive.dart';

part 'habit.g.dart';  // This will be generated by hive_generator

@HiveType(typeId: 0)
class Habit {
  @HiveField(0)
  final int id;
  
  @HiveField(1)
  final String name;

  @HiveField(2)
  final String category;

  @HiveField(3)
  final int goal;

  @HiveField(4)
  int completedCount;

  Habit({
    required this.id,
    required this.name,
    required this.category,
    required this.goal,
    this.completedCount = 0,
  });
}
